# Generated by Django 4.2.5 on 2023-09-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('stu_f_name', models.CharField(max_length=30)),
                ('stu_l_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('stu_message', models.TextField()),
            ],
        ),
    ]
