# Generated by Django 4.2.5 on 2023-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytodods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
